# Laptop-specific settings
#
exec --no-startup-id xrandr --output eDP --primary --dpi 96 --auto

exec_always --no-startup-id picom -b

# Blueman applet for Bluetooth management
exec_always --no-startup-id blueman-applet
exec_always --no-startup-id sh -c 'sleep 2; rfkill unblock bluetooth; bluetoothctl power on'

# Восстановление обоев на всех экранах (с небольшой задержкой)
exec_always --no-startup-id sleep 2; nitrogen --restore
