[paths]
code = "Configs/vscode/vscode.toml"
nvim = "Configs/nvim/nvim.toml"
megasync = "Configs/megasync.toml"
pass = "Security/pass.toml"
ssh = "Security/ssh/ssh.toml"
git = "Security/git.toml"
manjaro = "Configs/manjaro.toml"
