work_dirs = [
	"Tools",
    "Downloads",
    "Security",
    "Documents",
    "Music",
    "Pictures",
    "Projects",
    "Videos",
    "Configs",
    "Obsidian",
    "BackUps",
    "VMs",
]

rc = "Work/Configs/rc"
profile = "Work/Configs/profile"
mimeapps_list = "Work/Configs/mimeapps.list"
rc_files = [
	".bashrc",
	".zshrc"
	]
delete_files = ".bash_profile"

