work_dirs = [
	"Tools",
    "Downloads",
    "Security",
    "Documents",
    "Music",
    "Pictures",
    "Projects",
    "Videos",
    "Configs",
    "Obsidian",
    "BackUps",
    "VMs",
]

rc = "Work/Configs/rc"
profile = "Work/Configs/profile"
mimeapps_list = "Work/Configs/mimeapps.list"
rc_files = [
	".bashrc",
	".zshrc"
	]
delete_files = ".bash_profile"

local_font_dir = ".local/share/fonts"
config_font_dir = "Work/Configs/fonts"
font_cache_files= ".cache/fontconfig/*"

trash_dir = "Work/Trash"

packages = "unzip lsof nmap"
