work_dirs = [
	"Tools",
    "Downloads",
    "Security",
    "Documents",
    "Music",
    "Pictures",
    "Projects",
    "Videos",
    "Configs",
    "Obsidian",
    "BackUps",
    "VMs",
]

rc = "Work/Configs/rc"
rc_files = [".bashrc", ".zshrc"]

profile = [".profile", "Work/Configs/profile"]
mimeapps_list = [".config/mimeapps.list", "Work/Configs/mimeapps.list"]
xresources= [".Xresources", "Work/Configs/Xresources"]

delete_files = ".bash_profile"

font_dir = [".local/share/fonts", "Work/Configs/fonts"]
font_cache_files = ".cache/fontconfig/*"

trash_dir = ".local/share/Trash"

packages = "trash-cli unzip lsof nmap"
