[manjaro_i3]

requirements = ["trash-cli", "manjaro-settings-manager", "materia-gtk-theme"]

requirements_2 = ["base-devel", "unzip", "font-manager", "galculator", "xorg-xev", "keepass"]

internet = ["google-chrome", "firefox", "lsof", "nmap, transmission-gtk"]

communication = ["slack-desktop", "zoom"]




[ubuntu]
