words = [
    "aur",
    "chatbots",
    "chmod",
    "chrono",
    "clippy",
    "dotenv",
    "gimli",
    "llm",
    "manjaro",
    "mcp",
    "overengineering",
    "pacman",
    "pyenv",
    "reusability",
    "rustup",
    "serde",
    "sila",
    "swo",
    "swp",
    "vscode",
    "yay",
]
