[packages]

unneeded = "bmenu palemoon"

sound = "alsa-utils pulseaudio pavucontrol"

requirements = "manjaro-settings-manager materia-gtk-theme matcha-gtk-theme"

requirements_2 = "base-devel font-manager galculator xorg-xev keepass"

internet = "google-chrome firefox lsof nmap transmission-gtk"

communication = "slack-desktop zoom telegram-desktop"


