# Desktop-specific settings
#
exec_always --no-startup-id xrandr --output HDMI-1 --mode 2560x1440 --pos 0x360 --rotate normal --brightness 0.7 --gamma 1.0:0.95:0.85 --output DP-1 --primary --mode 3840x2160 --pos 2560x0 --rotate normal --output DP-2 --mode 3840x2160 --pos 6400x0 --rotate normal

# Let the desktop use normal screen blanking and DPMS again.
exec --no-startup-id xset s on
exec --no-startup-id xset +dpms
exec_always --no-startup-id picom -b

# Фиксируем звук на центральном LG через Pro Audio
exec_always --no-startup-id pactl set-card-profile alsa_card.pci-0000_04_00.1 pro-audio
exec_always --no-startup-id pactl set-default-sink alsa_output.pci-0000_04_00.1.pro-output-7
