# Desktop-specific settings
#
exec_always --no-startup-id ~/.config/i3/scripts/monitor-layout-desktop

# Let the desktop use normal screen blanking and DPMS again.
exec --no-startup-id xset s on
exec --no-startup-id xset +dpms
exec_always --no-startup-id picom -b

# Фиксируем звук на центральном LG через Pro Audio
exec_always --no-startup-id pactl set-card-profile alsa_card.pci-0000_04_00.1 pro-audio
exec_always --no-startup-id pactl set-default-sink alsa_output.pci-0000_04_00.1.pro-output-7
