packages="code"

config_dir = [".config/Code - OSS/User/", "Work/Configs/vscode/"]

config_files = ["settings.json", "keybindings.json"]

extensions = [
	"vscodevim.vim",                        #vim
    "asapdotid.manjaro-dark",				#theme
    "rust-lang.rust-analyzer",
    "pkief.material-icon-theme",
    "bungcip.better-toml",
    "serayuzgur.crates",
    "streetsidesoftware.code-spell-checker",
    "ms-azuretools.vscode-docker",
    "ms-python.python"
]
