#!/bin/bash

# Theme settings for Qt and GTK
export QT_QPA_PLATFORMTHEME=qt6ct
export QT_STYLE_OVERRIDE="kvantum"
export GTK_THEME="Matcha-dark-sea"
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

# Editor configuration
if command -v nvim >/dev/null 2>&1; then
    export EDITOR=/usr/bin/nvim
else
    export EDITOR=/usr/bin/nano
fi

# Browser configuration
export BROWSER=/usr/bin/google-chrome-stable

